version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REPO: todo-app
    EKS_CLUSTER: todo-cluster

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $ECR_REPO ./app
      - docker tag $ECR_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing image & deploying"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
      - - kubectl apply -f k8s/ --validate=false

